@startuml

left to right direction

class Brand {
    -id: int
    -carBrand: string
    -cars: Collection<Car>
   +insertBrand() : JsonResponse
   +deleteBrand() : JsonResponse
   +listAllBrands() : JsonResponse
}

class Car {
    -id: int
    -carModel: string
    -matriculation: string
    -identify: Brand
    -numberPlaces: int
    +insertCar() : JsonResponse
    +deleteCar() : JsonResponse
    +listAllCars() : JsonResponse
}

class City {
    -id: int
    -name: string
    -zipCode: string
    -trips: Collection<Trip>
    -tripsArrival: Collection<Trip>
    -students: Collection<Student>
    +insertCity() : JsonResponse
    +deleteCity() : JsonResponse
    +listAllCities() : JsonResponse
    +listAllZipCodes() : JsonResponse
}

class Student {
    -id: int
    -firstname: string
    -name: string
    -phone: string
    -email: string
    -register: User
    -participate: Collection<Trip>
    -drive: Collection<Trip>
    -live: City
    -possess: Car
    +insertStudent() : JsonResponse
    +updateStudent() : JsonResponse
    +deleteStudent() : JsonResponse
    +getStudent() : JsonResponse
    +listAllStudents() : JsonResponse
}

class Trip {
    -id: int
    -kmDistance: float
    -travelDate: DateTime
    -placesOffered: int
    -students: Collection<Student>
    -student: Student
    -startingTrip: City
    -arrivalTrip: City
    +insertTrip() : JsonResponse
    +searchTrip() : JsonResponse
    +listAllTrips() : JsonResponse
    +deleteTrip() : JsonResponse
    +insertParticipation() : JsonResponse
    +listAllParticipations() : JsonResponse
    +deleteParticipation() : JsonResponse
    +getDriverOnTrip() : JsonResponse
    +getStudentOnTrips() : JsonResponse
}

class User {
    -id: int
    -login: string
    -roles: array
    -password: string
    -token: string
    +register() : JsonResponse
    +login() : JsonResponse
}



Student "0.1" -- "1" User : register

Student "*" -- "*" Trip : participate
Student "1" -- "*" Trip : drive
Car "0.1" -- "1" Student : possess
City "1" -- "*" Student : live

Brand "1" -- "*" Car : identify

City "1" -- "*" Trip : starting
City "1" -- "*" Trip : arrival






@enduml